### ISSUE TITLE
Images and graphics not showing

### ISSUE THREAD

**Issue by JoshMout** [Asiern/SpeedrunHub#82]
![Screenshot_20230812_225239_SpeedrunHub](https://github.com/Asiern/SpeedrunHub/assets/22785444/a95cdda2-7daf-4198-a9a3-46e13e42d7d0)
![Screenshot_20230812_225226_SpeedrunHub](https://github.com/Asiern/SpeedrunHub/assets/22785444/ae5c82dc-118c-4184-a015-b1468c10a76b)
No images or graphics show on any page in the app.

**Comment by Asiern** [comment]
Hello,

I hope you're having a good day. I wanted to sincerely thank you for taking the time to notify me about the issue with the images in my app through the GitHub issue. Your feedback is truly valuable to me and helps me improve the quality of the application.

I've investigated the problem and identified that the images aren't displaying due to a change in the Speedrun.com API. As a result, I need to update the endpoints to address this issue. I really appreciate your patience and understanding as I work to resolve this inconvenience.

Please stay tuned for updates on the GitHub repository, as I'll be working diligently to fix this problem as soon as possible. If you have any further observations or suggestions, please don't hesitate to share. Your collaboration is essential in making the app function optimally!

Best regards,
Asiern

**Comment by JoshMout** [comment]
Great! Thank you!

**Comment by Asiern** [comment]
Speedrun.con finally updated their API, the issue should be fixed.
